development:
  adapter: postgresql
  encoding: unicode
  database: photography_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: alex
  password: Il2ep!!!

test:
  adapter: postgresql
  encoding: unicode
  database: photography_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: alex
  password: Il2ep!!!
